on:
  push:
    branches:
      - main
      - feature-**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go-API
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o hello cmd/main.go
      - name: Run
        run: ./hello